# Generated by Django 5.0.6 on 2024-05-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Firearm', 'firearm'), ('Ammunition', 'ammunition'), ('Attachments', 'attachments')], default='Firearm', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default='This is an Item', max_length=500, null=True),
        ),
    ]
