# Generated by Django 5.0.6 on 2024-05-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_name_product_gunmodel_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pistol', 'Firearm - Pistol'), ('Shotgun', 'Firearm - Shotgun'), ('Rifle', 'Firearm - Rifle'), ('Magazine', 'Accessories - Magazine'), ('Optics', 'Accessories - Optics'), ('Knives', 'Accessories - Knives'), ('Ammunition', 'Ammunition')], default='Firearm', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[], default='', max_length=50, null=True),
        ),
    ]
