# Generated by Django 5.0.6 on 2024-05-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_supplier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
