# Generated by Django 5.0.6 on 2024-05-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_supplier_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='contact_number',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
