# Generated by Django 5.0.6 on 2024-05-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_buyer_name_alter_buyer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='color',
        ),
        migrations.RemoveField(
            model_name='order',
            name='design',
        ),
        migrations.RemoveField(
            model_name='order',
            name='drop',
        ),
        migrations.RemoveField(
            model_name='order',
            name='season',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
